apiVersion: v1
kind: Service
metadata:
  name: delicious-recipes-service
  labels:
    app: delicious-recipes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: delicious-recipes
